# Prometheus Configuration for Fusionpact DevOps Challenge

global:
  scrape_interval: 15s
  evaluation_interval: 15s
  external_labels:
    monitor: 'fusionpact-monitor'

# Alerting configuration (optional - can be extended)
alerting:
  alertmanagers:
    - static_configs:
        - targets: []

# Load rules once and periodically evaluate them
rule_files:
  # - "alerts.yml"

# Scrape configurations
scrape_configs:
  # Prometheus itself
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']
        labels:
          service: 'prometheus'

  # FastAPI Backend Application
  - job_name: 'backend'
    metrics_path: '/metrics'
    static_configs:
      - targets: ['backend:8000']
        labels:
          service: 'backend-api'
          environment: 'production'

  # Node Exporter - Infrastructure Metrics
  - job_name: 'node-exporter'
    static_configs:
      - targets: ['node-exporter:9100']
        labels:
          service: 'infrastructure'
          type: 'node-exporter'

  # cAdvisor - Container Metrics
  - job_name: 'cadvisor'
    static_configs:
      - targets: ['cadvisor:8080']
        labels:
          service: 'containers'
          type: 'cadvisor'
